version: "3.8"

services:
  web:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ng serve --host=0.0.0.0 --port=4200


  jsondb:
    image: "clue/json-server"
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:80"
    command: -w db.json
